DROP TABLE ADMINISTRATOR
GO

CREATE TABLE ADMINISTRATOR(
   AdminId INT NOT NULL IDENTITY(0,1),
   FirstName VARCHAR(25) NULL,
   LastName VARCHAR(25) NULL,
   AdminDesc TEXT NULL,
   PRIMARY KEY ( AdminId )
);
GO

CREATE TABLE LOGIN(
   LoginId INT NOT NULL IDENTITY(0,1),
   UserName VARCHAR(20) UNIQUE NOT NULL,
   UserPass VARCHAR(12) NOT NULL,
   PassHash var
   PassSalt
   PRIMARY KEY ( LoginId ),
   FOREIGN KEY ( AdminId ) REFERENCES ADMINISTRATOR(AdminId)
);
GO